steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', '$_IMAGE-jsbuild:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', '$_IMAGE:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '--cache-from',
            '$_IMAGE-jsbuild:latest',
            '-t', '$_IMAGE-jsbuild:latest',
            '-t', '$_IMAGE-jsbuild:$TAG_NAME',
            '-f', 'etc/docker/jsbuild',
            '.'
        ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'run',
            '-v', '/workspace/release:/app/release:rw',
            '$_IMAGE-jsbuild'
        ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '--cache-from',
            '$_IMAGE:latest',
            '-t', '$_IMAGE:latest',
            '-t', '$_IMAGE:$TAG_NAME',
            '-f', 'etc/docker/Dockerfile',
            '.'
        ]
images: ['$_IMAGE-jsbuild', '$_IMAGE']
